AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless_Melody_Generate_Music

Parameters:
  Version:
    Type: String
    Default: 'v1'
  Stage:
    Type: String
    Default: 'dev'
    AllowedValues:
    - dev 
    - stage 
    - prod
  Project: 
    Type: String
    Default: 'melody_generate_music'
  DockerPath:
    Type: String
    Default: './src'


Globals:
  Function:
    Timeout: 180
    MemorySize: 2048

Resources:
  MyDockerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}'
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /music # Replace this for most descriptive path
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: !Sub '${DockerPath}'
      DockerTag: 'latest'
    Tags: 
      version: !Ref Version
      stage: !Ref Stage
      project: !Ref Project 


Outputs:
  MyCustomDockerApi:
    Description: 'API Gateway Prod endpoint URL for My Docker Lambda function'
    Value: !Sub 'https://${MyDockerLambda}.execute-api.${AWS::Region}.amazonaws.com/Prod/music/'