EMOTIONS = [
    "delighted", "gloomy", "relaxed", "tense"
]

NUM_NOTES = 128
NUM_EMOTION = 4

NUM_OCTAVES = 4
OCTAVE = 12

BEATS_PER_BAR = 4
NOTES_PER_BEAT = 4
NOTES_PER_BAR = NOTES_PER_BEAT * BEATS_PER_BAR

IN_SEQ_LEN = 128
OUT_SEQ_LEN = 128

EMOTION_UNITS = 64
NOTE_UNITS = 3
OCTAVE_UNITS = 64
TIME_AXIS_UNITS = 256
NOTE_AXIS_UNITS = 128

TIME_AXIS_LAYERS = 2
NOTE_AXIS_LAYERS = 2

DATA_DIR = "../data"
DATASET_DIR = "../dataset"

MODEL_DIR = "../models"
MODEL_NAME = "model.h5"
Model_PATH = f"{MODEL_DIR}/{MODEL_NAME}"

OUTPUT_DAR = "../generate"